// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// QrTarget is the predicate function for qrtarget builders.
type QrTarget func(*sql.Selector)

// TargetType is the predicate function for targettype builders.
type TargetType func(*sql.Selector)
