// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"qr.mandacode.com/redirect/ent/predicate"
	"qr.mandacode.com/redirect/ent/qrtarget"
	"qr.mandacode.com/redirect/ent/targettype"
)

// TargetTypeQuery is the builder for querying TargetType entities.
type TargetTypeQuery struct {
	config
	ctx           *QueryContext
	order         []targettype.OrderOption
	inters        []Interceptor
	predicates    []predicate.TargetType
	withQrTargets *QrTargetQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TargetTypeQuery builder.
func (ttq *TargetTypeQuery) Where(ps ...predicate.TargetType) *TargetTypeQuery {
	ttq.predicates = append(ttq.predicates, ps...)
	return ttq
}

// Limit the number of records to be returned by this query.
func (ttq *TargetTypeQuery) Limit(limit int) *TargetTypeQuery {
	ttq.ctx.Limit = &limit
	return ttq
}

// Offset to start from.
func (ttq *TargetTypeQuery) Offset(offset int) *TargetTypeQuery {
	ttq.ctx.Offset = &offset
	return ttq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ttq *TargetTypeQuery) Unique(unique bool) *TargetTypeQuery {
	ttq.ctx.Unique = &unique
	return ttq
}

// Order specifies how the records should be ordered.
func (ttq *TargetTypeQuery) Order(o ...targettype.OrderOption) *TargetTypeQuery {
	ttq.order = append(ttq.order, o...)
	return ttq
}

// QueryQrTargets chains the current query on the "qr_targets" edge.
func (ttq *TargetTypeQuery) QueryQrTargets() *QrTargetQuery {
	query := (&QrTargetClient{config: ttq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ttq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(targettype.Table, targettype.FieldID, selector),
			sqlgraph.To(qrtarget.Table, qrtarget.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, targettype.QrTargetsTable, targettype.QrTargetsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TargetType entity from the query.
// Returns a *NotFoundError when no TargetType was found.
func (ttq *TargetTypeQuery) First(ctx context.Context) (*TargetType, error) {
	nodes, err := ttq.Limit(1).All(setContextOp(ctx, ttq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{targettype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ttq *TargetTypeQuery) FirstX(ctx context.Context) *TargetType {
	node, err := ttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TargetType ID from the query.
// Returns a *NotFoundError when no TargetType ID was found.
func (ttq *TargetTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttq.Limit(1).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{targettype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ttq *TargetTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := ttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TargetType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TargetType entity is found.
// Returns a *NotFoundError when no TargetType entities are found.
func (ttq *TargetTypeQuery) Only(ctx context.Context) (*TargetType, error) {
	nodes, err := ttq.Limit(2).All(setContextOp(ctx, ttq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{targettype.Label}
	default:
		return nil, &NotSingularError{targettype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ttq *TargetTypeQuery) OnlyX(ctx context.Context) *TargetType {
	node, err := ttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TargetType ID in the query.
// Returns a *NotSingularError when more than one TargetType ID is found.
// Returns a *NotFoundError when no entities are found.
func (ttq *TargetTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ttq.Limit(2).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{targettype.Label}
	default:
		err = &NotSingularError{targettype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ttq *TargetTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TargetTypes.
func (ttq *TargetTypeQuery) All(ctx context.Context) ([]*TargetType, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryAll)
	if err := ttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TargetType, *TargetTypeQuery]()
	return withInterceptors[[]*TargetType](ctx, ttq, qr, ttq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ttq *TargetTypeQuery) AllX(ctx context.Context) []*TargetType {
	nodes, err := ttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TargetType IDs.
func (ttq *TargetTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ttq.ctx.Unique == nil && ttq.path != nil {
		ttq.Unique(true)
	}
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryIDs)
	if err = ttq.Select(targettype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ttq *TargetTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := ttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ttq *TargetTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryCount)
	if err := ttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ttq, querierCount[*TargetTypeQuery](), ttq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ttq *TargetTypeQuery) CountX(ctx context.Context) int {
	count, err := ttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ttq *TargetTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryExist)
	switch _, err := ttq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ttq *TargetTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := ttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TargetTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ttq *TargetTypeQuery) Clone() *TargetTypeQuery {
	if ttq == nil {
		return nil
	}
	return &TargetTypeQuery{
		config:        ttq.config,
		ctx:           ttq.ctx.Clone(),
		order:         append([]targettype.OrderOption{}, ttq.order...),
		inters:        append([]Interceptor{}, ttq.inters...),
		predicates:    append([]predicate.TargetType{}, ttq.predicates...),
		withQrTargets: ttq.withQrTargets.Clone(),
		// clone intermediate query.
		sql:  ttq.sql.Clone(),
		path: ttq.path,
	}
}

// WithQrTargets tells the query-builder to eager-load the nodes that are connected to
// the "qr_targets" edge. The optional arguments are used to configure the query builder of the edge.
func (ttq *TargetTypeQuery) WithQrTargets(opts ...func(*QrTargetQuery)) *TargetTypeQuery {
	query := (&QrTargetClient{config: ttq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ttq.withQrTargets = query
	return ttq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TargetType.Query().
//		GroupBy(targettype.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ttq *TargetTypeQuery) GroupBy(field string, fields ...string) *TargetTypeGroupBy {
	ttq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TargetTypeGroupBy{build: ttq}
	grbuild.flds = &ttq.ctx.Fields
	grbuild.label = targettype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type"`
//	}
//
//	client.TargetType.Query().
//		Select(targettype.FieldType).
//		Scan(ctx, &v)
func (ttq *TargetTypeQuery) Select(fields ...string) *TargetTypeSelect {
	ttq.ctx.Fields = append(ttq.ctx.Fields, fields...)
	sbuild := &TargetTypeSelect{TargetTypeQuery: ttq}
	sbuild.label = targettype.Label
	sbuild.flds, sbuild.scan = &ttq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TargetTypeSelect configured with the given aggregations.
func (ttq *TargetTypeQuery) Aggregate(fns ...AggregateFunc) *TargetTypeSelect {
	return ttq.Select().Aggregate(fns...)
}

func (ttq *TargetTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ttq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ttq); err != nil {
				return err
			}
		}
	}
	for _, f := range ttq.ctx.Fields {
		if !targettype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ttq.path != nil {
		prev, err := ttq.path(ctx)
		if err != nil {
			return err
		}
		ttq.sql = prev
	}
	return nil
}

func (ttq *TargetTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TargetType, error) {
	var (
		nodes       = []*TargetType{}
		_spec       = ttq.querySpec()
		loadedTypes = [1]bool{
			ttq.withQrTargets != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TargetType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TargetType{config: ttq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ttq.withQrTargets; query != nil {
		if err := ttq.loadQrTargets(ctx, query, nodes,
			func(n *TargetType) { n.Edges.QrTargets = []*QrTarget{} },
			func(n *TargetType, e *QrTarget) { n.Edges.QrTargets = append(n.Edges.QrTargets, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ttq *TargetTypeQuery) loadQrTargets(ctx context.Context, query *QrTargetQuery, nodes []*TargetType, init func(*TargetType), assign func(*TargetType, *QrTarget)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TargetType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(qrtarget.FieldTargetTypeID)
	}
	query.Where(predicate.QrTarget(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(targettype.QrTargetsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TargetTypeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "target_type_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ttq *TargetTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ttq.querySpec()
	_spec.Node.Columns = ttq.ctx.Fields
	if len(ttq.ctx.Fields) > 0 {
		_spec.Unique = ttq.ctx.Unique != nil && *ttq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ttq.driver, _spec)
}

func (ttq *TargetTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(targettype.Table, targettype.Columns, sqlgraph.NewFieldSpec(targettype.FieldID, field.TypeInt))
	_spec.From = ttq.sql
	if unique := ttq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ttq.path != nil {
		_spec.Unique = true
	}
	if fields := ttq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, targettype.FieldID)
		for i := range fields {
			if fields[i] != targettype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ttq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ttq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ttq *TargetTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ttq.driver.Dialect())
	t1 := builder.Table(targettype.Table)
	columns := ttq.ctx.Fields
	if len(columns) == 0 {
		columns = targettype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ttq.sql != nil {
		selector = ttq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ttq.ctx.Unique != nil && *ttq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ttq.predicates {
		p(selector)
	}
	for _, p := range ttq.order {
		p(selector)
	}
	if offset := ttq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ttq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TargetTypeGroupBy is the group-by builder for TargetType entities.
type TargetTypeGroupBy struct {
	selector
	build *TargetTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ttgb *TargetTypeGroupBy) Aggregate(fns ...AggregateFunc) *TargetTypeGroupBy {
	ttgb.fns = append(ttgb.fns, fns...)
	return ttgb
}

// Scan applies the selector query and scans the result into the given value.
func (ttgb *TargetTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ttgb.build.ctx, ent.OpQueryGroupBy)
	if err := ttgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TargetTypeQuery, *TargetTypeGroupBy](ctx, ttgb.build, ttgb, ttgb.build.inters, v)
}

func (ttgb *TargetTypeGroupBy) sqlScan(ctx context.Context, root *TargetTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ttgb.fns))
	for _, fn := range ttgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ttgb.flds)+len(ttgb.fns))
		for _, f := range *ttgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ttgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TargetTypeSelect is the builder for selecting fields of TargetType entities.
type TargetTypeSelect struct {
	*TargetTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tts *TargetTypeSelect) Aggregate(fns ...AggregateFunc) *TargetTypeSelect {
	tts.fns = append(tts.fns, fns...)
	return tts
}

// Scan applies the selector query and scans the result into the given value.
func (tts *TargetTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tts.ctx, ent.OpQuerySelect)
	if err := tts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TargetTypeQuery, *TargetTypeSelect](ctx, tts.TargetTypeQuery, tts, tts.inters, v)
}

func (tts *TargetTypeSelect) sqlScan(ctx context.Context, root *TargetTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tts.fns))
	for _, fn := range tts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
