// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// QrTargetsColumns holds the columns for the "qr_targets" table.
	QrTargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "target", Type: field.TypeString, Nullable: true},
		{Name: "target_type_id", Type: field.TypeInt},
	}
	// QrTargetsTable holds the schema information for the "qr_targets" table.
	QrTargetsTable = &schema.Table{
		Name:       "qr_targets",
		Columns:    QrTargetsColumns,
		PrimaryKey: []*schema.Column{QrTargetsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "qr_targets_target_types_qr_targets",
				Columns:    []*schema.Column{QrTargetsColumns[2]},
				RefColumns: []*schema.Column{TargetTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TargetTypesColumns holds the columns for the "target_types" table.
	TargetTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString, Unique: true},
	}
	// TargetTypesTable holds the schema information for the "target_types" table.
	TargetTypesTable = &schema.Table{
		Name:       "target_types",
		Columns:    TargetTypesColumns,
		PrimaryKey: []*schema.Column{TargetTypesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QrTargetsTable,
		TargetTypesTable,
	}
)

func init() {
	QrTargetsTable.ForeignKeys[0].RefTable = TargetTypesTable
}
