// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"qr.mandacode.com/redirect/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"qr.mandacode.com/redirect/ent/qrtarget"
	"qr.mandacode.com/redirect/ent/targettype"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// QrTarget is the client for interacting with the QrTarget builders.
	QrTarget *QrTargetClient
	// TargetType is the client for interacting with the TargetType builders.
	TargetType *TargetTypeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.QrTarget = NewQrTargetClient(c.config)
	c.TargetType = NewTargetTypeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		QrTarget:   NewQrTargetClient(cfg),
		TargetType: NewTargetTypeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		QrTarget:   NewQrTargetClient(cfg),
		TargetType: NewTargetTypeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		QrTarget.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.QrTarget.Use(hooks...)
	c.TargetType.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.QrTarget.Intercept(interceptors...)
	c.TargetType.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *QrTargetMutation:
		return c.QrTarget.mutate(ctx, m)
	case *TargetTypeMutation:
		return c.TargetType.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// QrTargetClient is a client for the QrTarget schema.
type QrTargetClient struct {
	config
}

// NewQrTargetClient returns a client for the QrTarget from the given config.
func NewQrTargetClient(c config) *QrTargetClient {
	return &QrTargetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `qrtarget.Hooks(f(g(h())))`.
func (c *QrTargetClient) Use(hooks ...Hook) {
	c.hooks.QrTarget = append(c.hooks.QrTarget, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `qrtarget.Intercept(f(g(h())))`.
func (c *QrTargetClient) Intercept(interceptors ...Interceptor) {
	c.inters.QrTarget = append(c.inters.QrTarget, interceptors...)
}

// Create returns a builder for creating a QrTarget entity.
func (c *QrTargetClient) Create() *QrTargetCreate {
	mutation := newQrTargetMutation(c.config, OpCreate)
	return &QrTargetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of QrTarget entities.
func (c *QrTargetClient) CreateBulk(builders ...*QrTargetCreate) *QrTargetCreateBulk {
	return &QrTargetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QrTargetClient) MapCreateBulk(slice any, setFunc func(*QrTargetCreate, int)) *QrTargetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QrTargetCreateBulk{err: fmt.Errorf("calling to QrTargetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QrTargetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QrTargetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for QrTarget.
func (c *QrTargetClient) Update() *QrTargetUpdate {
	mutation := newQrTargetMutation(c.config, OpUpdate)
	return &QrTargetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QrTargetClient) UpdateOne(qt *QrTarget) *QrTargetUpdateOne {
	mutation := newQrTargetMutation(c.config, OpUpdateOne, withQrTarget(qt))
	return &QrTargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QrTargetClient) UpdateOneID(id uuid.UUID) *QrTargetUpdateOne {
	mutation := newQrTargetMutation(c.config, OpUpdateOne, withQrTargetID(id))
	return &QrTargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for QrTarget.
func (c *QrTargetClient) Delete() *QrTargetDelete {
	mutation := newQrTargetMutation(c.config, OpDelete)
	return &QrTargetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QrTargetClient) DeleteOne(qt *QrTarget) *QrTargetDeleteOne {
	return c.DeleteOneID(qt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QrTargetClient) DeleteOneID(id uuid.UUID) *QrTargetDeleteOne {
	builder := c.Delete().Where(qrtarget.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QrTargetDeleteOne{builder}
}

// Query returns a query builder for QrTarget.
func (c *QrTargetClient) Query() *QrTargetQuery {
	return &QrTargetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQrTarget},
		inters: c.Interceptors(),
	}
}

// Get returns a QrTarget entity by its id.
func (c *QrTargetClient) Get(ctx context.Context, id uuid.UUID) (*QrTarget, error) {
	return c.Query().Where(qrtarget.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QrTargetClient) GetX(ctx context.Context, id uuid.UUID) *QrTarget {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTargettype queries the targettype edge of a QrTarget.
func (c *QrTargetClient) QueryTargettype(qt *QrTarget) *TargetTypeQuery {
	query := (&TargetTypeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := qt.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(qrtarget.Table, qrtarget.FieldID, id),
			sqlgraph.To(targettype.Table, targettype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, qrtarget.TargettypeTable, qrtarget.TargettypeColumn),
		)
		fromV = sqlgraph.Neighbors(qt.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QrTargetClient) Hooks() []Hook {
	return c.hooks.QrTarget
}

// Interceptors returns the client interceptors.
func (c *QrTargetClient) Interceptors() []Interceptor {
	return c.inters.QrTarget
}

func (c *QrTargetClient) mutate(ctx context.Context, m *QrTargetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QrTargetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QrTargetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QrTargetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QrTargetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown QrTarget mutation op: %q", m.Op())
	}
}

// TargetTypeClient is a client for the TargetType schema.
type TargetTypeClient struct {
	config
}

// NewTargetTypeClient returns a client for the TargetType from the given config.
func NewTargetTypeClient(c config) *TargetTypeClient {
	return &TargetTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `targettype.Hooks(f(g(h())))`.
func (c *TargetTypeClient) Use(hooks ...Hook) {
	c.hooks.TargetType = append(c.hooks.TargetType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `targettype.Intercept(f(g(h())))`.
func (c *TargetTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.TargetType = append(c.inters.TargetType, interceptors...)
}

// Create returns a builder for creating a TargetType entity.
func (c *TargetTypeClient) Create() *TargetTypeCreate {
	mutation := newTargetTypeMutation(c.config, OpCreate)
	return &TargetTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TargetType entities.
func (c *TargetTypeClient) CreateBulk(builders ...*TargetTypeCreate) *TargetTypeCreateBulk {
	return &TargetTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TargetTypeClient) MapCreateBulk(slice any, setFunc func(*TargetTypeCreate, int)) *TargetTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TargetTypeCreateBulk{err: fmt.Errorf("calling to TargetTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TargetTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TargetTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TargetType.
func (c *TargetTypeClient) Update() *TargetTypeUpdate {
	mutation := newTargetTypeMutation(c.config, OpUpdate)
	return &TargetTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TargetTypeClient) UpdateOne(tt *TargetType) *TargetTypeUpdateOne {
	mutation := newTargetTypeMutation(c.config, OpUpdateOne, withTargetType(tt))
	return &TargetTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TargetTypeClient) UpdateOneID(id int) *TargetTypeUpdateOne {
	mutation := newTargetTypeMutation(c.config, OpUpdateOne, withTargetTypeID(id))
	return &TargetTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TargetType.
func (c *TargetTypeClient) Delete() *TargetTypeDelete {
	mutation := newTargetTypeMutation(c.config, OpDelete)
	return &TargetTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TargetTypeClient) DeleteOne(tt *TargetType) *TargetTypeDeleteOne {
	return c.DeleteOneID(tt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TargetTypeClient) DeleteOneID(id int) *TargetTypeDeleteOne {
	builder := c.Delete().Where(targettype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TargetTypeDeleteOne{builder}
}

// Query returns a query builder for TargetType.
func (c *TargetTypeClient) Query() *TargetTypeQuery {
	return &TargetTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTargetType},
		inters: c.Interceptors(),
	}
}

// Get returns a TargetType entity by its id.
func (c *TargetTypeClient) Get(ctx context.Context, id int) (*TargetType, error) {
	return c.Query().Where(targettype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TargetTypeClient) GetX(ctx context.Context, id int) *TargetType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryQrTargets queries the qr_targets edge of a TargetType.
func (c *TargetTypeClient) QueryQrTargets(tt *TargetType) *QrTargetQuery {
	query := (&QrTargetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := tt.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(targettype.Table, targettype.FieldID, id),
			sqlgraph.To(qrtarget.Table, qrtarget.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, targettype.QrTargetsTable, targettype.QrTargetsColumn),
		)
		fromV = sqlgraph.Neighbors(tt.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TargetTypeClient) Hooks() []Hook {
	return c.hooks.TargetType
}

// Interceptors returns the client interceptors.
func (c *TargetTypeClient) Interceptors() []Interceptor {
	return c.inters.TargetType
}

func (c *TargetTypeClient) mutate(ctx context.Context, m *TargetTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TargetTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TargetTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TargetTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TargetTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TargetType mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		QrTarget, TargetType []ent.Hook
	}
	inters struct {
		QrTarget, TargetType []ent.Interceptor
	}
)
