// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"qr.mandacode.com/redirect/ent/predicate"
	"qr.mandacode.com/redirect/ent/qrtarget"
)

// QrTargetDelete is the builder for deleting a QrTarget entity.
type QrTargetDelete struct {
	config
	hooks    []Hook
	mutation *QrTargetMutation
}

// Where appends a list predicates to the QrTargetDelete builder.
func (qtd *QrTargetDelete) Where(ps ...predicate.QrTarget) *QrTargetDelete {
	qtd.mutation.Where(ps...)
	return qtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qtd *QrTargetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qtd.sqlExec, qtd.mutation, qtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qtd *QrTargetDelete) ExecX(ctx context.Context) int {
	n, err := qtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qtd *QrTargetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(qrtarget.Table, sqlgraph.NewFieldSpec(qrtarget.FieldID, field.TypeUUID))
	if ps := qtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qtd.mutation.done = true
	return affected, err
}

// QrTargetDeleteOne is the builder for deleting a single QrTarget entity.
type QrTargetDeleteOne struct {
	qtd *QrTargetDelete
}

// Where appends a list predicates to the QrTargetDelete builder.
func (qtdo *QrTargetDeleteOne) Where(ps ...predicate.QrTarget) *QrTargetDeleteOne {
	qtdo.qtd.mutation.Where(ps...)
	return qtdo
}

// Exec executes the deletion query.
func (qtdo *QrTargetDeleteOne) Exec(ctx context.Context) error {
	n, err := qtdo.qtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{qrtarget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qtdo *QrTargetDeleteOne) ExecX(ctx context.Context) {
	if err := qtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
