// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"qr.mandacode.com/redirect/ent/predicate"
	"qr.mandacode.com/redirect/ent/qrtarget"
	"qr.mandacode.com/redirect/ent/targettype"
)

// QrTargetQuery is the builder for querying QrTarget entities.
type QrTargetQuery struct {
	config
	ctx            *QueryContext
	order          []qrtarget.OrderOption
	inters         []Interceptor
	predicates     []predicate.QrTarget
	withTargettype *TargetTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QrTargetQuery builder.
func (qtq *QrTargetQuery) Where(ps ...predicate.QrTarget) *QrTargetQuery {
	qtq.predicates = append(qtq.predicates, ps...)
	return qtq
}

// Limit the number of records to be returned by this query.
func (qtq *QrTargetQuery) Limit(limit int) *QrTargetQuery {
	qtq.ctx.Limit = &limit
	return qtq
}

// Offset to start from.
func (qtq *QrTargetQuery) Offset(offset int) *QrTargetQuery {
	qtq.ctx.Offset = &offset
	return qtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qtq *QrTargetQuery) Unique(unique bool) *QrTargetQuery {
	qtq.ctx.Unique = &unique
	return qtq
}

// Order specifies how the records should be ordered.
func (qtq *QrTargetQuery) Order(o ...qrtarget.OrderOption) *QrTargetQuery {
	qtq.order = append(qtq.order, o...)
	return qtq
}

// QueryTargettype chains the current query on the "targettype" edge.
func (qtq *QrTargetQuery) QueryTargettype() *TargetTypeQuery {
	query := (&TargetTypeClient{config: qtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := qtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := qtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(qrtarget.Table, qrtarget.FieldID, selector),
			sqlgraph.To(targettype.Table, targettype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, qrtarget.TargettypeTable, qrtarget.TargettypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(qtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QrTarget entity from the query.
// Returns a *NotFoundError when no QrTarget was found.
func (qtq *QrTargetQuery) First(ctx context.Context) (*QrTarget, error) {
	nodes, err := qtq.Limit(1).All(setContextOp(ctx, qtq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{qrtarget.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qtq *QrTargetQuery) FirstX(ctx context.Context) *QrTarget {
	node, err := qtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QrTarget ID from the query.
// Returns a *NotFoundError when no QrTarget ID was found.
func (qtq *QrTargetQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = qtq.Limit(1).IDs(setContextOp(ctx, qtq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{qrtarget.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qtq *QrTargetQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := qtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QrTarget entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QrTarget entity is found.
// Returns a *NotFoundError when no QrTarget entities are found.
func (qtq *QrTargetQuery) Only(ctx context.Context) (*QrTarget, error) {
	nodes, err := qtq.Limit(2).All(setContextOp(ctx, qtq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{qrtarget.Label}
	default:
		return nil, &NotSingularError{qrtarget.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qtq *QrTargetQuery) OnlyX(ctx context.Context) *QrTarget {
	node, err := qtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QrTarget ID in the query.
// Returns a *NotSingularError when more than one QrTarget ID is found.
// Returns a *NotFoundError when no entities are found.
func (qtq *QrTargetQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = qtq.Limit(2).IDs(setContextOp(ctx, qtq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{qrtarget.Label}
	default:
		err = &NotSingularError{qrtarget.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qtq *QrTargetQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := qtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QrTargets.
func (qtq *QrTargetQuery) All(ctx context.Context) ([]*QrTarget, error) {
	ctx = setContextOp(ctx, qtq.ctx, ent.OpQueryAll)
	if err := qtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QrTarget, *QrTargetQuery]()
	return withInterceptors[[]*QrTarget](ctx, qtq, qr, qtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qtq *QrTargetQuery) AllX(ctx context.Context) []*QrTarget {
	nodes, err := qtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QrTarget IDs.
func (qtq *QrTargetQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if qtq.ctx.Unique == nil && qtq.path != nil {
		qtq.Unique(true)
	}
	ctx = setContextOp(ctx, qtq.ctx, ent.OpQueryIDs)
	if err = qtq.Select(qrtarget.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qtq *QrTargetQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := qtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qtq *QrTargetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qtq.ctx, ent.OpQueryCount)
	if err := qtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qtq, querierCount[*QrTargetQuery](), qtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qtq *QrTargetQuery) CountX(ctx context.Context) int {
	count, err := qtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qtq *QrTargetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qtq.ctx, ent.OpQueryExist)
	switch _, err := qtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qtq *QrTargetQuery) ExistX(ctx context.Context) bool {
	exist, err := qtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QrTargetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qtq *QrTargetQuery) Clone() *QrTargetQuery {
	if qtq == nil {
		return nil
	}
	return &QrTargetQuery{
		config:         qtq.config,
		ctx:            qtq.ctx.Clone(),
		order:          append([]qrtarget.OrderOption{}, qtq.order...),
		inters:         append([]Interceptor{}, qtq.inters...),
		predicates:     append([]predicate.QrTarget{}, qtq.predicates...),
		withTargettype: qtq.withTargettype.Clone(),
		// clone intermediate query.
		sql:  qtq.sql.Clone(),
		path: qtq.path,
	}
}

// WithTargettype tells the query-builder to eager-load the nodes that are connected to
// the "targettype" edge. The optional arguments are used to configure the query builder of the edge.
func (qtq *QrTargetQuery) WithTargettype(opts ...func(*TargetTypeQuery)) *QrTargetQuery {
	query := (&TargetTypeClient{config: qtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	qtq.withTargettype = query
	return qtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TargetTypeID int `json:"target_type_id"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QrTarget.Query().
//		GroupBy(qrtarget.FieldTargetTypeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qtq *QrTargetQuery) GroupBy(field string, fields ...string) *QrTargetGroupBy {
	qtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QrTargetGroupBy{build: qtq}
	grbuild.flds = &qtq.ctx.Fields
	grbuild.label = qrtarget.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TargetTypeID int `json:"target_type_id"`
//	}
//
//	client.QrTarget.Query().
//		Select(qrtarget.FieldTargetTypeID).
//		Scan(ctx, &v)
func (qtq *QrTargetQuery) Select(fields ...string) *QrTargetSelect {
	qtq.ctx.Fields = append(qtq.ctx.Fields, fields...)
	sbuild := &QrTargetSelect{QrTargetQuery: qtq}
	sbuild.label = qrtarget.Label
	sbuild.flds, sbuild.scan = &qtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QrTargetSelect configured with the given aggregations.
func (qtq *QrTargetQuery) Aggregate(fns ...AggregateFunc) *QrTargetSelect {
	return qtq.Select().Aggregate(fns...)
}

func (qtq *QrTargetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qtq); err != nil {
				return err
			}
		}
	}
	for _, f := range qtq.ctx.Fields {
		if !qrtarget.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qtq.path != nil {
		prev, err := qtq.path(ctx)
		if err != nil {
			return err
		}
		qtq.sql = prev
	}
	return nil
}

func (qtq *QrTargetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QrTarget, error) {
	var (
		nodes       = []*QrTarget{}
		_spec       = qtq.querySpec()
		loadedTypes = [1]bool{
			qtq.withTargettype != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QrTarget).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QrTarget{config: qtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := qtq.withTargettype; query != nil {
		if err := qtq.loadTargettype(ctx, query, nodes, nil,
			func(n *QrTarget, e *TargetType) { n.Edges.Targettype = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (qtq *QrTargetQuery) loadTargettype(ctx context.Context, query *TargetTypeQuery, nodes []*QrTarget, init func(*QrTarget), assign func(*QrTarget, *TargetType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QrTarget)
	for i := range nodes {
		fk := nodes[i].TargetTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(targettype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "target_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (qtq *QrTargetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qtq.querySpec()
	_spec.Node.Columns = qtq.ctx.Fields
	if len(qtq.ctx.Fields) > 0 {
		_spec.Unique = qtq.ctx.Unique != nil && *qtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qtq.driver, _spec)
}

func (qtq *QrTargetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(qrtarget.Table, qrtarget.Columns, sqlgraph.NewFieldSpec(qrtarget.FieldID, field.TypeUUID))
	_spec.From = qtq.sql
	if unique := qtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qtq.path != nil {
		_spec.Unique = true
	}
	if fields := qtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrtarget.FieldID)
		for i := range fields {
			if fields[i] != qrtarget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if qtq.withTargettype != nil {
			_spec.Node.AddColumnOnce(qrtarget.FieldTargetTypeID)
		}
	}
	if ps := qtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qtq *QrTargetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qtq.driver.Dialect())
	t1 := builder.Table(qrtarget.Table)
	columns := qtq.ctx.Fields
	if len(columns) == 0 {
		columns = qrtarget.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qtq.sql != nil {
		selector = qtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qtq.ctx.Unique != nil && *qtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range qtq.predicates {
		p(selector)
	}
	for _, p := range qtq.order {
		p(selector)
	}
	if offset := qtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QrTargetGroupBy is the group-by builder for QrTarget entities.
type QrTargetGroupBy struct {
	selector
	build *QrTargetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qtgb *QrTargetGroupBy) Aggregate(fns ...AggregateFunc) *QrTargetGroupBy {
	qtgb.fns = append(qtgb.fns, fns...)
	return qtgb
}

// Scan applies the selector query and scans the result into the given value.
func (qtgb *QrTargetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qtgb.build.ctx, ent.OpQueryGroupBy)
	if err := qtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QrTargetQuery, *QrTargetGroupBy](ctx, qtgb.build, qtgb, qtgb.build.inters, v)
}

func (qtgb *QrTargetGroupBy) sqlScan(ctx context.Context, root *QrTargetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qtgb.fns))
	for _, fn := range qtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qtgb.flds)+len(qtgb.fns))
		for _, f := range *qtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QrTargetSelect is the builder for selecting fields of QrTarget entities.
type QrTargetSelect struct {
	*QrTargetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qts *QrTargetSelect) Aggregate(fns ...AggregateFunc) *QrTargetSelect {
	qts.fns = append(qts.fns, fns...)
	return qts
}

// Scan applies the selector query and scans the result into the given value.
func (qts *QrTargetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qts.ctx, ent.OpQuerySelect)
	if err := qts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QrTargetQuery, *QrTargetSelect](ctx, qts.QrTargetQuery, qts, qts.inters, v)
}

func (qts *QrTargetSelect) sqlScan(ctx context.Context, root *QrTargetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qts.fns))
	for _, fn := range qts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
